
[functions.chat-ai]
enabled = true
verify_jwt = true
import_map = "./functions/chat-ai/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chat-ai/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chat-ai/*.html" ]

[functions.sync-subscription-status]
enabled = true
verify_jwt = true
entrypoint = "./functions/sync-subscription-status/index.ts"

[functions.app-store-server-notifications]
enabled = true
verify_jwt = false
entrypoint = "./functions/app-store-server-notifications/index.ts"

[functions.delete-account]
enabled = true
verify_jwt = true
entrypoint = "./functions/delete-account/index.ts"

[functions.generate-onboarding-teaser]
enabled = true
verify_jwt = true
entrypoint = "./functions/generate-onboarding-teaser/index.ts"
