//
//  ReadinessChecklistViewModel.swift
//  Renaissance Mobile
//

import Foundation
import Observation

@Observable
class ReadinessChecklistViewModel {

    // MARK: - State

    var selectedProcedureId: String? {
        didSet { loadChecklist() }
    }

    var checklist: ProcedureChecklist?
    var expandedSections: Set<ChecklistSectionType> = [.candidacy]

    // MARK: - Private

    private var userId: String = ""
    private var completedItemIds: Set<String> = []

    // MARK: - Init

    init(userId: String, procedureId: String? = nil) {
        self.userId = userId
        self.selectedProcedureId = procedureId
        loadChecklist()
    }

    // MARK: - Checklist Loading

    private func loadChecklist() {
        guard let id = selectedProcedureId else {
            checklist = nil
            completedItemIds = []
            return
        }
        checklist = ReadinessData.checklist(for: id)
        completedItemIds = loadCompletedIds(for: id)
    }

    // MARK: - Completion State

    func isCompleted(_ item: ChecklistItem) -> Bool {
        completedItemIds.contains(item.id)
    }

    func toggle(_ item: ChecklistItem) {
        if completedItemIds.contains(item.id) {
            completedItemIds.remove(item.id)
        } else {
            completedItemIds.insert(item.id)
        }
        saveCompletedIds()
    }

    var completedCount: Int {
        guard let checklist else { return 0 }
        return checklist.allItemIds.filter { completedItemIds.contains($0) }.count
    }

    var totalCount: Int {
        checklist?.allItemIds.count ?? 0
    }

    var completionPercent: Double {
        guard totalCount > 0 else { return 0 }
        return Double(completedCount) / Double(totalCount)
    }

    // Non-warning items only (exclude red flags from progress tracking)
    var actionableCompletedCount: Int {
        guard let checklist else { return 0 }
        return checklist.sections
            .filter { !$0.isWarningSection }
            .flatMap { $0.items }
            .filter { completedItemIds.contains($0.id) }
            .count
    }

    var actionableTotalCount: Int {
        checklist?.sections
            .filter { !$0.isWarningSection }
            .flatMap { $0.items }
            .count ?? 0
    }

    // MARK: - Section Expansion

    func toggleSection(_ type: ChecklistSectionType) {
        if expandedSections.contains(type) {
            expandedSections.remove(type)
        } else {
            expandedSections.insert(type)
        }
    }

    func isSectionExpanded(_ type: ChecklistSectionType) -> Bool {
        expandedSections.contains(type)
    }

    // MARK: - Share

    func shareText() -> String {
        guard let checklist else { return "" }
        var lines: [String] = [
            "My \(checklist.displayName) Readiness Checklist",
            "Generated by Renaissance App",
            ""
        ]
        for section in checklist.sections {
            lines.append("--- \(section.title) ---")
            for item in section.items {
                let mark = isCompleted(item) ? "[x]" : "[ ]"
                lines.append("\(mark) \(item.text)")
            }
            lines.append("")
        }
        lines.append("Note: This checklist is for informational purposes only and does not constitute medical advice. Consult a licensed provider before any procedure.")
        return lines.joined(separator: "\n")
    }

    // MARK: - UserDefaults Persistence

    private func userDefaultsKey(for procedureId: String) -> String {
        "checklist_completed_\(userId)_\(procedureId)"
    }

    private func loadCompletedIds(for procedureId: String) -> Set<String> {
        let key = userDefaultsKey(for: procedureId)
        let stored = UserDefaults.standard.stringArray(forKey: key) ?? []
        return Set(stored)
    }

    private func saveCompletedIds() {
        guard let id = selectedProcedureId else { return }
        let key = userDefaultsKey(for: id)
        UserDefaults.standard.set(Array(completedItemIds), forKey: key)
    }
}
