//
//  RecoveryInsights.swift
//  Renaissance Mobile
//
//  Cross-entry AI insights model. Generated by the `generate-recovery-insights`
//  edge function which analyzes patterns across multiple journal entries.
//

import Foundation

// MARK: - Recovery Insights

struct RecoveryInsights: Codable {
    // AI-generated content
    let summary: String
    let trend: TrendDirection
    let flags: [InsightFlag]
    let encouragements: [String]
    let nextSteps: String?

    // Metadata — populated by RecoveryInsightsService, not the edge function
    var procedureId: String
    var procedureName: String
    var generatedAt: Date
    var entryCount: Int
}

// MARK: - Trend Direction

enum TrendDirection: String, Codable {
    case improving
    case stable
    case concerning

    var label: String {
        switch self {
        case .improving:  return "Improving"
        case .stable:     return "Stable"
        case .concerning: return "Needs Attention"
        }
    }

    var systemImage: String {
        switch self {
        case .improving:  return "arrow.up.right"
        case .stable:     return "minus"
        case .concerning: return "exclamationmark.triangle"
        }
    }
}

// MARK: - Insight Flag

struct InsightFlag: Codable {
    let severity: FlagSeverity
    let message: String
    let metric: String?
}

// MARK: - Flag Severity

enum FlagSeverity: String, Codable {
    case info
    case warning
    case urgent

    var systemImage: String {
        switch self {
        case .info:    return "info.circle"
        case .warning: return "exclamationmark.circle"
        case .urgent:  return "exclamationmark.triangle.fill"
        }
    }
}
